### ISSUE TITLE
建议1

### ISSUE THREAD

**Issue by nikkio0** [6etacat/xiaozhu-bot#1]
/salt "more salt is bad salt"
/sugar "more sugar is bad sugar"
/dislike "家暴" "奇葩说" 
/oinks5starhealthydiet “蔬菜炒坚果” “炸鸡” “猪足”
/oinksthought1"生育率很重要，多重要在座的各位不用我说了吧 Oink"
/oinksthought2 “夜骑带面罩会被误以为偷自行车，具体解决措施：避免靠近自行车群 Oink”

**Comment by 6etacat** [comment]
好的，会加进去的
